// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoAI.Data;

#nullable disable

namespace ToDoAI.Migrations
{
    [DbContext(typeof(ToDoAiAppDbContext))]
    [Migration("20231109141302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToDoAI.Models.InputFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ToDo")
                        .HasColumnType("longtext");

                    b.Property<string>("TypeOfHelp")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InputFields");
                });
#pragma warning restore 612, 618
        }
    }
}
